using InvestmentManager.Entities.Broker;
using InvestmentManager.Entities.Calculate;
using InvestmentManager.Entities.Market;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace InvestmentManager.Repository
{
    public class InvestmentContext : IdentityDbContext<IdentityUser>
    {
        #region DbSet
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountTransaction> AccountTransactions { get; set; }
        public DbSet<Comission> Comissions { get; set; }
        public DbSet<ComissionType> ComissionTypes { get; set; }
        public DbSet<Dividend> Dividends { get; set; }
        public DbSet<Isin> Isins { get; set; }
        public DbSet<ExchangeRate> ExchangeRates { get; set; }
        public DbSet<StockTransaction> StockTransactions { get; set; }
        public DbSet<TransactionStatus> TransactionStatuses { get; set; }
        public DbSet<Coefficient> Coefficients { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<BuyRecommendation> BuyRecommendations { get; set; }
        public DbSet<SellRecommendation> SellRecommendations { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<ReportSource> ReportSources { get; set; }
        public DbSet<ProxyAddress> ProxyAddresses { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Exchange> Exchanges { get; set; }
        public DbSet<Industry> Industries { get; set; }
        public DbSet<Lot> Lots { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<Sector> Sectors { get; set; }
        public DbSet<Ticker> Tickers { get; set; }
        #endregion

        public InvestmentContext(DbContextOptions<InvestmentContext> options) : base(options)
        {
            //Database.EnsureDeleted();
            //Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.Entity<StockTransaction>()
                .HasOne(x => x.Ticker)
                .WithMany(x => x.StockTransactions)
                .OnDelete(DeleteBehavior.Restrict);

            #region Base Data
            builder.Entity<Currency>().HasData(new Currency[]
                {
                    new Currency {Id = 1, Name = "usd" },
                    new Currency {Id = 2, Name = "rub" }
                });
            builder.Entity<Exchange>().HasData(new Exchange[]
                {
                    new Exchange {Id = 1, Name = "ММВБ", ProviderName = "moex", ProviderUri = "https://iss.moex.com/iss"},
                    new Exchange {Id = 2, Name = "СПБ", ProviderName = "tdameritrade", ProviderUri = "https://api.tdameritrade.com/v1/marketdata"},
                });
            builder.Entity<TransactionStatus>().HasData(new TransactionStatus[]
                {
                    new TransactionStatus{Id = 1, Name = "Пополнение"},
                    new TransactionStatus{Id = 2, Name = "Снятие"},
                    new TransactionStatus{Id = 3, Name = "Покупка"},
                    new TransactionStatus{Id = 4, Name = "Продажа"},
                    new TransactionStatus{Id = 5, Name = "Незавершенная покупка"},
                    new TransactionStatus{Id = 6, Name = "Незавершенная продажа"}
                });
            builder.Entity<ComissionType>().HasData(new ComissionType[]
                {
                    new ComissionType{Id = 1, Name = "НДФЛ" },
                    new ComissionType{Id = 2, Name = "Урегулирование сделок" },
                    new ComissionType{Id = 3, Name = "Вознаграждение компании" },
                    new ComissionType{Id = 4, Name = "Комиссия за займы \"овернайт ЦБ\"" },
                    new ComissionType{Id = 5, Name = "Вознаграждение компании (СВОП)" },
                    new ComissionType{Id = 6, Name = "Вознаграждение за обслуживание счета депо" },
                    new ComissionType{Id = 7, Name = "Оплата за вывод денежных средств" },
                    new ComissionType{Id = 8, Name = "Вознаграждение компании (репо)" },
                    new ComissionType{Id = 9, Name = "Комиссия Биржевой гуру" }
                });
            builder.Entity<Lot>().HasData(new Lot[]
                {
                    new Lot{Id = 1, Value = 1 },
                    new Lot{Id = 2, Value = 10 },
                    new Lot{Id = 3, Value = 100 },
                    new Lot{Id = 4, Value = 1000 },
                    new Lot{Id = 5, Value = 10000 }
                });
            builder.Entity<Industry>().HasData(new Industry[]
                {
                    new Industry{Id = 1, Name = "Пищевая промышленность"},
                    new Industry{Id = 2, Name = "Отдых"},
                    new Industry{Id = 3, Name = "Полупроводники"},
                    new Industry{Id = 4, Name = "Интегрированная нефтегазовая промышленность"},
                    new Industry{Id = 5, Name = "Производство и поставки медицинского оборудования"},
                    new Industry{Id = 6, Name = "Потребительские финансовые услуги"},
                    new Industry{Id = 7, Name = "Золото и серебро"},
                    new Industry{Id = 8, Name = "Аэрокосмическая и оборонная промышленность"},
                    new Industry{Id = 9, Name = "Эфирное и кабельное телевидение"},
                    new Industry{Id = 10, Name = "Биотехнологии и лекарства"},
                    new Industry{Id = 11, Name = "Компьютерные услуги"},
                    new Industry{Id = 12, Name = "Строительство-снабжение"},
                    new Industry{Id = 13, Name = "Напитки"},
                    new Industry{Id = 14, Name = "Научно-техническое приборостроение"},
                    new Industry{Id = 15, Name = "Газоснабжение"},
                    new Industry{Id = 16, Name = "Электроэнергетика"},
                    new Industry{Id = 17, Name = "Региональные банки"},
                    new Industry{Id = 18, Name = "Химическое производство"},
                    new Industry{Id = 19, Name = "Коммуникационное оборудование"},
                    new Industry{Id = 20, Name = "Разные промышленные товары"},
                    new Industry{Id = 21, Name = "Программное обеспечение и программирование"},
                    new Industry{Id = 22, Name = "Различные средства производства"},
                    new Industry{Id = 23, Name = "Автомобильная промышленность"},
                    new Industry{Id = 24, Name = "Деловые услуги"},
                    new Industry{Id = 25, Name = "Услуги связи"},
                    new Industry{Id = 26, Name = "Розничная торговля"},
                    new Industry{Id = 27, Name = "Нерудная промышленность"},
                    new Industry{Id = 28, Name = "Воздушные перевозки"},
                    new Industry{Id = 29, Name = "Металлодобывающая промышленность"},
                    new Industry{Id = 30, Name = "Нефтегазовая промышленность"}
                });
            builder.Entity<Sector>().HasData(new Sector[]
                {
                    new Sector{Id = 1, Name = "Сырье"},
                    new Sector{Id = 2, Name = "Средства производства"},
                    new Sector{Id = 3, Name = "Технологии"},
                    new Sector{Id = 4, Name = "Коммунальные услуги"},
                    new Sector{Id = 5, Name = "Энергетика"},
                    new Sector{Id = 6, Name = "Цикличные компании"},
                    new Sector{Id = 7, Name = "Финансы"},
                    new Sector{Id = 8, Name = "Нецикличные компании"},
                    new Sector{Id = 9, Name = "Здравоохранение"},
                    new Sector{Id = 10, Name = "Услуги"},
                    new Sector{Id = 11, Name = "Транспорт"}
                });
            builder.Entity<Company>().HasData(new Company[]
            {
                new Company{Id = 1,     IndustryId = 12, SectorId = 2, Name ="3M"},
                new Company{Id = 2,     IndustryId = 5,  SectorId = 9, Name ="Abbott Labs"},
                new Company{Id = 3,     IndustryId = 21, SectorId = 3, Name ="Adobe"},
                new Company{Id = 4,     IndustryId = 18, SectorId = 1, Name ="Air Products and Chemicals"},
                new Company{Id = 5,     IndustryId = 26, SectorId = 10, Name ="Alibaba"},
                new Company{Id = 6,     IndustryId = 5,  SectorId = 9, Name ="Align Technology"},
                new Company{Id = 7,     IndustryId = 11, SectorId = 3, Name ="Alphabet"},
                new Company{Id = 8,     IndustryId = 26, SectorId = 10, Name ="Amazon"},
                new Company{Id = 9,     IndustryId = 6,  SectorId = 7, Name ="American Express"},
                new Company{Id = 10,    IndustryId = 19, SectorId = 3, Name ="Apple"},
                new Company{Id = 11,    IndustryId = 3,  SectorId = 3, Name ="Applied Materials"},
                new Company{Id = 12,    IndustryId = 25, SectorId = 10, Name ="AT&T"},
                new Company{Id = 13,    IndustryId = 17, SectorId = 7, Name ="Bank of America"},
                new Company{Id = 14,    IndustryId = 5,  SectorId = 9, Name ="Becton Dickinson"},
                new Company{Id = 15,    IndustryId = 26, SectorId = 10, Name ="Best Buy"},
                new Company{Id = 16,    IndustryId = 10, SectorId = 9, Name ="Biogen"},
                new Company{Id = 17,    IndustryId = 8,  SectorId = 2, Name ="Boeing"},
                new Company{Id = 18,    IndustryId = 2,  SectorId = 10, Name ="Carnival"},
                new Company{Id = 19,    IndustryId = 25, SectorId = 10, Name ="Charter Communications"},
                new Company{Id = 20,    IndustryId = 4,  SectorId = 5, Name ="Chevron"},
                new Company{Id = 21,    IndustryId = 19, SectorId = 3, Name ="Cisco"},
                new Company{Id = 22,    IndustryId = 13, SectorId = 8, Name ="Coca-Cola"},
                new Company{Id = 23,    IndustryId = 25, SectorId = 10, Name ="Comcast"},
                new Company{Id = 24,    IndustryId = 4,  SectorId = 5, Name ="ConocoPhillips"},
                new Company{Id = 25,    IndustryId = 22, SectorId = 2, Name ="Cummins"},
                new Company{Id = 26,    IndustryId = 14, SectorId = 3, Name ="Danaher"},
                new Company{Id = 27,    IndustryId = 16, SectorId = 4, Name ="Dominion Energy"},
                new Company{Id = 28,    IndustryId = 20, SectorId = 1, Name ="Dover"},
                new Company{Id = 29,    IndustryId = 14, SectorId = 3, Name ="Emerson Electric"},
                new Company{Id = 30,    IndustryId = 11, SectorId = 3, Name ="Facebook"},
                new Company{Id = 31,    IndustryId = 6,  SectorId = 7, Name ="Fidelity"},
                new Company{Id = 32,    IndustryId = 23, SectorId = 6, Name ="Ford"},
                new Company{Id = 33,    IndustryId = 22, SectorId = 2, Name ="General Electric"},
                new Company{Id = 34,    IndustryId = 1,  SectorId = 8, Name ="General Mills"},
                new Company{Id = 35,    IndustryId = 6,  SectorId = 7, Name ="Global Payments"},
                new Company{Id = 36,    IndustryId = 8,  SectorId = 2, Name ="Honeywell"},
                new Company{Id = 37,    IndustryId = 11, SectorId = 3, Name ="IBM"},
                new Company{Id = 38,    IndustryId = 14, SectorId = 3, Name ="Illumina"},
                new Company{Id = 39,    IndustryId = 3,  SectorId = 3, Name ="Intel"},
                new Company{Id = 40,    IndustryId = 10, SectorId = 9, Name ="Johnson & Johnson"},
                new Company{Id = 41,    IndustryId = 13, SectorId = 8, Name ="Keurig Dr Pepper"},
                new Company{Id = 42,    IndustryId = 15, SectorId = 4, Name ="Kinder Morgan"},
                new Company{Id = 43,    IndustryId = 1,  SectorId = 8, Name ="Kraft Heinz"},
                new Company{Id = 44,    IndustryId = 22, SectorId = 2, Name ="Lam Research"},
                new Company{Id = 45,    IndustryId = 7,  SectorId = 1, Name ="Lenozoloto"},
                new Company{Id = 46,    IndustryId = 2,  SectorId = 10, Name ="Live Nation"},
                new Company{Id = 47,    IndustryId = 8,  SectorId = 2, Name ="Lockheed Martin"},
                new Company{Id = 48,    IndustryId = 12, SectorId = 2, Name ="Masco"},
                new Company{Id = 49,    IndustryId = 6,  SectorId = 7, Name ="Mastercard"},
                new Company{Id = 50,    IndustryId = 5,  SectorId = 9, Name ="Medtronic"},
                new Company{Id = 51,    IndustryId = 10, SectorId = 9, Name ="Merck & Co"},
                new Company{Id = 52,    IndustryId = 3,  SectorId = 3, Name ="Micron Technology"},
                new Company{Id = 53,    IndustryId = 21, SectorId = 3, Name ="Microsoft"},
                new Company{Id = 54,    IndustryId = 1,  SectorId = 8, Name ="Mondelez"},
                new Company{Id = 55,    IndustryId = 9,  SectorId = 10, Name ="Netflix"},
                new Company{Id = 56,    IndustryId = 7,  SectorId = 1, Name ="Newmont"},
                new Company{Id = 57,    IndustryId = 16, SectorId = 4, Name ="NextEra"},
                new Company{Id = 58,    IndustryId = 19, SectorId = 3, Name ="Northrop Grumman"},
                new Company{Id = 59,    IndustryId = 2,  SectorId = 10, Name ="Norwegian Cruise Line"},
                new Company{Id = 60,    IndustryId = 3,  SectorId = 3, Name ="Nvidia"},
                new Company{Id = 61,    IndustryId = 21, SectorId = 3, Name ="Oracle"},
                new Company{Id = 62,    IndustryId = 21, SectorId = 3, Name ="Palo Alto Networks"},
                new Company{Id = 63,    IndustryId = 20, SectorId = 1, Name ="Parker-Hannifin"},
                new Company{Id = 64,    IndustryId = 6,  SectorId = 7, Name ="PayPal"},
                new Company{Id = 65,    IndustryId = 13, SectorId = 8, Name ="Pepsi"},
                new Company{Id = 66,    IndustryId = 10, SectorId = 9, Name ="Pfizer"},
                new Company{Id = 67,    IndustryId = 7,  SectorId = 1, Name ="Polymetal"},
                new Company{Id = 68,    IndustryId = 19, SectorId = 3, Name ="Qualcomm"},
                new Company{Id = 69,    IndustryId = 8,  SectorId = 2, Name ="Raytheon"},
                new Company{Id = 70,    IndustryId = 20, SectorId = 1, Name ="Reliance Steel"},
                new Company{Id = 71,    IndustryId = 2,  SectorId = 10, Name ="Royal Caribbean Cruises"},
                new Company{Id = 72,    IndustryId = 12, SectorId = 2, Name ="RPM"},
                new Company{Id = 73,    IndustryId = 21, SectorId = 3, Name ="Salesforce"},
                new Company{Id = 74,    IndustryId = 18, SectorId = 1, Name ="Sherwin-Williams"},
                new Company{Id = 75,    IndustryId = 9,  SectorId = 10, Name ="Sirius XM"},
                new Company{Id = 76,    IndustryId = 16, SectorId = 4, Name ="Southern"},
                new Company{Id = 77,    IndustryId = 29, SectorId = 1, Name ="Southern Copper"},
                new Company{Id = 78,    IndustryId = 28, SectorId = 11, Name ="Southwest Airlines"},
                new Company{Id = 79,    IndustryId = 6,  SectorId = 7, Name ="TCS Group"},
                new Company{Id = 80,    IndustryId = 23, SectorId = 6, Name ="Tesla"},
                new Company{Id = 81,    IndustryId = 11, SectorId = 3, Name ="Twitter"},
                new Company{Id = 82,    IndustryId = 25, SectorId = 10, Name ="Verizon"},
                new Company{Id = 83,    IndustryId = 10, SectorId = 9, Name ="Vertex"},
                new Company{Id = 84,    IndustryId = 24, SectorId = 10, Name ="Visa"},
                new Company{Id = 85,    IndustryId = 9,  SectorId = 10, Name ="Walt Disney"},
                new Company{Id = 86,    IndustryId = 17, SectorId = 7, Name ="Wells Fargo"},
                new Company{Id = 87,    IndustryId = 26, SectorId = 10, Name ="X5"},
                new Company{Id = 88,    IndustryId = 11, SectorId = 3, Name ="Yandex"},
                new Company{Id = 89,    IndustryId = 11, SectorId = 3, Name ="YY"},
                new Company{Id = 90,    IndustryId = 18, SectorId = 1, Name ="Акрон"},
                new Company{Id = 91,    IndustryId = 27, SectorId = 1, Name ="Алроса"},
                new Company{Id = 92,    IndustryId = 17, SectorId = 7, Name ="ВТБ"},
                new Company{Id = 93,    IndustryId = 15, SectorId = 4, Name ="Газпром"},
                new Company{Id = 94,    IndustryId = 26, SectorId = 10, Name ="Детский мир"},
                new Company{Id = 95,    IndustryId = 23, SectorId = 6, Name ="ЗИЛ"},
                new Company{Id = 96,    IndustryId = 10, SectorId = 9, Name ="Институт Стволовых Клеток Человека"},
                new Company{Id = 97,    IndustryId = 8,  SectorId = 2, Name ="Иркут"},
                new Company{Id = 98,    IndustryId = 22, SectorId = 2, Name ="Камаз"},
                new Company{Id = 99,    IndustryId = 18, SectorId = 1, Name ="КуйбышевАзот"},
                new Company{Id = 100,   IndustryId = 14, SectorId = 3, Name ="Левенгук"},
                new Company{Id = 101,   IndustryId = 26, SectorId = 10, Name ="Лента"},
                new Company{Id = 102,   IndustryId = 4,  SectorId = 5, Name ="Лукойл"},
                new Company{Id = 103,   IndustryId = 25, SectorId = 10, Name ="Мегафон"},
                new Company{Id = 104,   IndustryId = 29, SectorId = 1, Name ="Мечел"},
                new Company{Id = 105,   IndustryId = 20, SectorId = 1, Name ="ММК"},
                new Company{Id = 106,   IndustryId = 17, SectorId = 7, Name ="Московский кредитный банк"},
                new Company{Id = 107,   IndustryId = 16, SectorId = 4, Name ="Мосэнерго"},
                new Company{Id = 108,   IndustryId = 16, SectorId = 4, Name ="МРСК Волги"},
                new Company{Id = 109,   IndustryId = 25, SectorId = 10, Name ="МТС"},
                new Company{Id = 110,   IndustryId = 1,  SectorId = 8, Name ="НКХП"},
                new Company{Id = 111,   IndustryId = 4,  SectorId = 5, Name ="Новатэк"},
                new Company{Id = 112,   IndustryId = 29, SectorId = 1, Name ="Норильский никель"},
                new Company{Id = 113,   IndustryId = 8,  SectorId = 2, Name ="Объединенная авиастроительная корпорация"},
                new Company{Id = 114,   IndustryId = 22, SectorId = 2, Name ="ОМЗ"},
                new Company{Id = 115,   IndustryId = 7,  SectorId = 1, Name ="Полюс"},
                new Company{Id = 116,   IndustryId = 8,  SectorId = 2, Name ="РКК Энергия"},
                new Company{Id = 117,   IndustryId = 17, SectorId = 7, Name ="Росбанк"},
                new Company{Id = 118,   IndustryId = 4,  SectorId = 5, Name ="Роснефть"},
                new Company{Id = 119,   IndustryId = 25, SectorId = 10, Name ="Ростелеком"},
                new Company{Id = 120,   IndustryId = 16, SectorId = 4, Name ="РусГидро"},
                new Company{Id = 121,   IndustryId = 17, SectorId = 7, Name ="Сбербанк"},
                new Company{Id = 122,   IndustryId = 29, SectorId = 1, Name ="Северсталь"},
                new Company{Id = 123,   IndustryId = 7,  SectorId = 1, Name ="Селигдар"},
                new Company{Id = 124,   IndustryId = 23, SectorId = 6, Name ="Соллерс"},
                new Company{Id = 125,   IndustryId = 30, SectorId = 5, Name ="Сургутнефтегаз"},
                new Company{Id = 126,   IndustryId = 22, SectorId = 2, Name ="ТЗА"},
                new Company{Id = 127,   IndustryId = 12, SectorId = 2, Name ="ТМК"},
                new Company{Id = 128,   IndustryId = 18, SectorId = 1, Name ="ФосАгро"},
                new Company{Id = 129,   IndustryId = 20, SectorId = 1, Name ="Челябинский металлургический комбинат"},
                new Company{Id = 130,   IndustryId = 12, SectorId = 2, Name ="ЧТПЗ"},
                new Company{Id = 131,   IndustryId = 16, SectorId = 4, Name ="Энел"}
            });
            builder.Entity<Ticker>().HasData(new Ticker[]
            {
                new Ticker{Id = 1,   CompanyId = 1,  ExchangeId = 2,  LotId = 1, Name = "MMM",    },
                new Ticker{Id = 2,   CompanyId = 2,  ExchangeId = 2,  LotId = 1, Name = "ABT",    },
                new Ticker{Id = 3,   CompanyId = 3,  ExchangeId = 2,  LotId = 1, Name = "ADBE",   },
                new Ticker{Id = 4,   CompanyId = 4,  ExchangeId = 2,  LotId = 1, Name = "APD",    },
                new Ticker{Id = 5,   CompanyId = 5,  ExchangeId = 2,  LotId = 1, Name = "BABA",   },
                new Ticker{Id = 6,   CompanyId = 6,  ExchangeId = 2,  LotId = 1, Name = "ALGN",   },
                new Ticker{Id = 7,   CompanyId = 7,  ExchangeId = 2,  LotId = 1, Name = "GOOG",   },
                new Ticker{Id = 8,   CompanyId = 8,  ExchangeId = 2,  LotId = 1, Name = "AMZN",   },
                new Ticker{Id = 9,   CompanyId = 9,  ExchangeId = 2,  LotId = 1, Name = "AXP",    },
                new Ticker{Id = 10,  CompanyId = 10, ExchangeId = 2,  LotId = 1, Name = "AAPL",   },
                new Ticker{Id = 11,  CompanyId = 11, ExchangeId = 2,  LotId = 1, Name = "AMAT",   },
                new Ticker{Id = 12,  CompanyId = 12, ExchangeId = 2,  LotId = 1, Name = "T",      },
                new Ticker{Id = 13,  CompanyId = 13, ExchangeId = 2,  LotId = 1, Name = "BAC",    },
                new Ticker{Id = 14,  CompanyId = 14, ExchangeId = 2,  LotId = 1, Name = "BDX",    },
                new Ticker{Id = 15,  CompanyId = 15, ExchangeId = 2,  LotId = 1, Name = "BBY",    },
                new Ticker{Id = 16,  CompanyId = 16, ExchangeId = 2,  LotId = 1, Name = "BIIB",   },
                new Ticker{Id = 17,  CompanyId = 17, ExchangeId = 2,  LotId = 1, Name = "BA",     },
                new Ticker{Id = 18,  CompanyId = 18, ExchangeId = 2,  LotId = 1, Name = "CCL",    },
                new Ticker{Id = 19,  CompanyId = 19, ExchangeId = 2,  LotId = 1, Name = "CHTR",   },
                new Ticker{Id = 20,  CompanyId = 20, ExchangeId = 2,  LotId = 1, Name = "CVX",    },
                new Ticker{Id = 21,  CompanyId = 21, ExchangeId = 2,  LotId = 1, Name = "CSCO",   },
                new Ticker{Id = 22,  CompanyId = 22, ExchangeId = 2,  LotId = 1, Name = "KO",     },
                new Ticker{Id = 23,  CompanyId = 23, ExchangeId = 2,  LotId = 1, Name = "CMCSA",  },
                new Ticker{Id = 24,  CompanyId = 24, ExchangeId = 2,  LotId = 1, Name = "COP",    },
                new Ticker{Id = 25,  CompanyId = 25, ExchangeId = 2,  LotId = 1, Name = "CMI",    },
                new Ticker{Id = 26,  CompanyId = 26, ExchangeId = 2,  LotId = 1, Name = "DHR",    },
                new Ticker{Id = 27,  CompanyId = 27, ExchangeId = 2,  LotId = 1, Name = "D",      },
                new Ticker{Id = 28,  CompanyId = 28, ExchangeId = 2,  LotId = 1, Name = "DOV",    },
                new Ticker{Id = 29,  CompanyId = 29, ExchangeId = 2,  LotId = 1, Name = "EMR",    },
                new Ticker{Id = 30,  CompanyId = 30, ExchangeId = 2,  LotId = 1, Name = "FB",     },
                new Ticker{Id = 31,  CompanyId = 31, ExchangeId = 2,  LotId = 1, Name = "FIS",    },
                new Ticker{Id = 32,  CompanyId = 32, ExchangeId = 2,  LotId = 1, Name = "F",      },
                new Ticker{Id = 33,  CompanyId = 33, ExchangeId = 2,  LotId = 1, Name = "GE",     },
                new Ticker{Id = 34,  CompanyId = 34, ExchangeId = 2,  LotId = 1, Name = "GIS",    },
                new Ticker{Id = 35,  CompanyId = 35, ExchangeId = 2,  LotId = 1, Name = "GPN",    },
                new Ticker{Id = 36,  CompanyId = 36, ExchangeId = 2,  LotId = 1, Name = "HON",    },
                new Ticker{Id = 37,  CompanyId = 37, ExchangeId = 2,  LotId = 1, Name = "IBM",    },
                new Ticker{Id = 38,  CompanyId = 38, ExchangeId = 2,  LotId = 1, Name = "ILMN",   },
                new Ticker{Id = 39,  CompanyId = 39, ExchangeId = 2,  LotId = 1, Name = "INTC",   },
                new Ticker{Id = 40,  CompanyId = 40, ExchangeId = 2,  LotId = 1, Name = "JNJ",    },
                new Ticker{Id = 41,  CompanyId = 41, ExchangeId = 2,  LotId = 1, Name = "KDP",    },
                new Ticker{Id = 42,  CompanyId = 42, ExchangeId = 2,  LotId = 1, Name = "KMI",    },
                new Ticker{Id = 43,  CompanyId = 43, ExchangeId = 2,  LotId = 1, Name = "KHC",    },
                new Ticker{Id = 44,  CompanyId = 44, ExchangeId = 2,  LotId = 1, Name = "LRCX",   },
                new Ticker{Id = 45,  CompanyId = 45, ExchangeId = 1,  LotId = 1, Name = "LNZL",   },
                new Ticker{Id = 46,  CompanyId = 46, ExchangeId = 2,  LotId = 1, Name = "LYV",    },
                new Ticker{Id = 47,  CompanyId = 47, ExchangeId = 2,  LotId = 1, Name = "LMT",    },
                new Ticker{Id = 48,  CompanyId = 48, ExchangeId = 2,  LotId = 1, Name = "MAS",    },
                new Ticker{Id = 49,  CompanyId = 49, ExchangeId = 2,  LotId = 1, Name = "MA",     },
                new Ticker{Id = 50,  CompanyId = 50, ExchangeId = 2,  LotId = 1, Name = "MDT",    },
                new Ticker{Id = 51,  CompanyId = 51, ExchangeId = 2,  LotId = 1, Name = "MRK",    },
                new Ticker{Id = 52,  CompanyId = 52, ExchangeId = 2,  LotId = 1, Name = "MU",     },
                new Ticker{Id = 53,  CompanyId = 53, ExchangeId = 2,  LotId = 1, Name = "MSFT",   },
                new Ticker{Id = 54,  CompanyId = 54, ExchangeId = 2,  LotId = 1, Name = "MDLZ",   },
                new Ticker{Id = 55,  CompanyId = 55, ExchangeId = 2,  LotId = 1, Name = "NFLX",   },
                new Ticker{Id = 56,  CompanyId = 56, ExchangeId = 2,  LotId = 1, Name = "NEM",    },
                new Ticker{Id = 57,  CompanyId = 57, ExchangeId = 2,  LotId = 1, Name = "NEE",    },
                new Ticker{Id = 58,  CompanyId = 58, ExchangeId = 2,  LotId = 1, Name = "NOC",    },
                new Ticker{Id = 59,  CompanyId = 59, ExchangeId = 2,  LotId = 1, Name = "NCLH",   },
                new Ticker{Id = 60,  CompanyId = 60, ExchangeId = 2,  LotId = 1, Name = "NVDA",   },
                new Ticker{Id = 61,  CompanyId = 61, ExchangeId = 2,  LotId = 1, Name = "ORCL",   },
                new Ticker{Id = 62,  CompanyId = 62, ExchangeId = 2,  LotId = 1, Name = "PANW",   },
                new Ticker{Id = 63,  CompanyId = 63, ExchangeId = 2,  LotId = 1, Name = "PH",     },
                new Ticker{Id = 64,  CompanyId = 64, ExchangeId = 2,  LotId = 1, Name = "PYPL",   },
                new Ticker{Id = 65,  CompanyId = 65, ExchangeId = 2,  LotId = 1, Name = "PEP",    },
                new Ticker{Id = 66,  CompanyId = 66, ExchangeId = 2,  LotId = 1, Name = "PFE",    },
                new Ticker{Id = 67,  CompanyId = 67, ExchangeId = 1,  LotId = 1, Name = "POLY",   },
                new Ticker{Id = 68,  CompanyId = 68, ExchangeId = 2,  LotId = 1, Name = "QCOM",   },
                new Ticker{Id = 69,  CompanyId = 69, ExchangeId = 2,  LotId = 1, Name = "RTX",    },
                new Ticker{Id = 70,  CompanyId = 70, ExchangeId = 2,  LotId = 1, Name = "RS",     },
                new Ticker{Id = 71,  CompanyId = 71, ExchangeId = 2,  LotId = 1, Name = "RCL",    },
                new Ticker{Id = 72,  CompanyId = 72, ExchangeId = 2,  LotId = 1, Name = "RPM",    },
                new Ticker{Id = 73,  CompanyId = 73, ExchangeId = 2,  LotId = 1, Name = "CRM",    },
                new Ticker{Id = 74,  CompanyId = 74, ExchangeId = 2,  LotId = 1, Name = "SHW",    },
                new Ticker{Id = 75,  CompanyId = 75, ExchangeId = 2,  LotId = 1, Name = "SIRI",   },
                new Ticker{Id = 76,  CompanyId = 76, ExchangeId = 2,  LotId = 1, Name = "SO",     },
                new Ticker{Id = 77,  CompanyId = 77, ExchangeId = 2,  LotId = 1, Name = "SCCO",   },
                new Ticker{Id = 78,  CompanyId = 78, ExchangeId = 2,  LotId = 1, Name = "LUV",    },
                new Ticker{Id = 79,  CompanyId = 79, ExchangeId = 1,  LotId = 1, Name = "TCSG",   },
                new Ticker{Id = 80,  CompanyId = 80, ExchangeId = 2,  LotId = 1, Name = "TSLA",   },
                new Ticker{Id = 81,  CompanyId = 81, ExchangeId = 2,  LotId = 1, Name = "TWTR",   },
                new Ticker{Id = 82,  CompanyId = 82, ExchangeId = 2,  LotId = 1, Name = "VZ",     },
                new Ticker{Id = 83,  CompanyId = 83, ExchangeId = 2,  LotId = 1, Name = "VRTX",   },
                new Ticker{Id = 84,  CompanyId = 84, ExchangeId = 2,  LotId = 1, Name = "V",      },
                new Ticker{Id = 85,  CompanyId = 85, ExchangeId = 2,  LotId = 1, Name = "DIS",    },
                new Ticker{Id = 86,  CompanyId = 86, ExchangeId = 2,  LotId = 1, Name = "WFC",    },
                new Ticker{Id = 87,  CompanyId = 87, ExchangeId = 1,  LotId = 1, Name = "FIVE",   },
                new Ticker{Id = 88,  CompanyId = 88, ExchangeId = 2,  LotId = 1, Name = "YNDX",   },
                new Ticker{Id = 89,  CompanyId = 89, ExchangeId = 2,  LotId = 1, Name = "YY",     },
                new Ticker{Id = 90,  CompanyId = 90, ExchangeId = 1,  LotId = 1, Name = "AKRN",   },
                new Ticker{Id = 91,  CompanyId = 91, ExchangeId = 1,  LotId = 2, Name = "ALRS",   },
                new Ticker{Id = 92,  CompanyId = 92, ExchangeId = 1,  LotId = 5, Name = "VTBR",   },
                new Ticker{Id = 93,  CompanyId = 93, ExchangeId = 1,  LotId = 2, Name = "GAZP",   },
                new Ticker{Id = 94,  CompanyId = 94, ExchangeId = 1,  LotId = 2, Name = "DSKY",   },
                new Ticker{Id = 95,  CompanyId = 95, ExchangeId = 1,  LotId = 1, Name = "ZILL",   },
                new Ticker{Id = 96,  CompanyId = 96, ExchangeId = 1,  LotId = 3, Name = "ISKJ",   },
                new Ticker{Id = 97,  CompanyId = 97, ExchangeId = 1,  LotId = 3, Name = "IRKT",   },
                new Ticker{Id = 98,  CompanyId = 98, ExchangeId = 1,  LotId = 2, Name = "KMAZ",   },
                new Ticker{Id = 99,  CompanyId = 99, ExchangeId = 1,  LotId = 2, Name = "KAZT",   },
                new Ticker{Id = 100, CompanyId = 100, ExchangeId = 1, LotId = 3, Name = "LVHK",   },
                new Ticker{Id = 101, CompanyId = 101, ExchangeId = 1, LotId = 1, Name = "LNTA",   },
                new Ticker{Id = 102, CompanyId = 102, ExchangeId = 1, LotId = 1, Name = "LKOH",   },
                new Ticker{Id = 103, CompanyId = 103, ExchangeId = 1, LotId = 1, Name = "MFON",   },
                new Ticker{Id = 104, CompanyId = 104, ExchangeId = 1, LotId = 1, Name = "MTLR",   },
                new Ticker{Id = 105, CompanyId = 105, ExchangeId = 1, LotId = 3, Name = "MAGN",   },
                new Ticker{Id = 106, CompanyId = 106, ExchangeId = 1, LotId = 3, Name = "CBOM",   },
                new Ticker{Id = 107, CompanyId = 107, ExchangeId = 1, LotId = 4, Name = "MSNG",   },
                new Ticker{Id = 108, CompanyId = 108, ExchangeId = 1, LotId = 5, Name = "MRKV",   },
                new Ticker{Id = 109, CompanyId = 109, ExchangeId = 1, LotId = 2, Name = "MTSS",   },
                new Ticker{Id = 110, CompanyId = 110, ExchangeId = 1, LotId = 2, Name = "NKHP",   },
                new Ticker{Id = 111, CompanyId = 111, ExchangeId = 1, LotId = 1, Name = "NVTK",   },
                new Ticker{Id = 112, CompanyId = 112, ExchangeId = 1, LotId = 1, Name = "GMKN",   },
                new Ticker{Id = 113, CompanyId = 113, ExchangeId = 1, LotId = 4, Name = "UNAC",   },
                new Ticker{Id = 114, CompanyId = 114, ExchangeId = 1, LotId = 1, Name = "OMZZP",  },
                new Ticker{Id = 115, CompanyId = 115, ExchangeId = 1, LotId = 1, Name = "PLZL",   },
                new Ticker{Id = 116, CompanyId = 116, ExchangeId = 1, LotId = 1, Name = "RKKE",   },
                new Ticker{Id = 117, CompanyId = 117, ExchangeId = 1, LotId = 2, Name = "ROSB",   },
                new Ticker{Id = 118, CompanyId = 118, ExchangeId = 1, LotId = 2, Name = "ROSN",   },
                new Ticker{Id = 119, CompanyId = 119, ExchangeId = 1, LotId = 2, Name = "RTKM",   },
                new Ticker{Id = 120, CompanyId = 120, ExchangeId = 1, LotId = 4, Name = "HYDR",   },
                new Ticker{Id = 121, CompanyId = 121, ExchangeId = 1, LotId = 2, Name = "SBER",   },
                new Ticker{Id = 122, CompanyId = 122, ExchangeId = 1, LotId = 1, Name = "CHMF",   },
                new Ticker{Id = 123, CompanyId = 123, ExchangeId = 1, LotId = 3, Name = "SELG",   },
                new Ticker{Id = 124, CompanyId = 124, ExchangeId = 1, LotId = 2, Name = "SVAV",   },
                new Ticker{Id = 125, CompanyId = 125, ExchangeId = 1, LotId = 3, Name = "SNGS",   },
                new Ticker{Id = 126, CompanyId = 126, ExchangeId = 1, LotId = 2, Name = "TUZA",   },
                new Ticker{Id = 127, CompanyId = 127, ExchangeId = 1, LotId = 2, Name = "TRMK",   },
                new Ticker{Id = 128, CompanyId = 128, ExchangeId = 1, LotId = 1, Name = "PHOR",   },
                new Ticker{Id = 129, CompanyId = 129, ExchangeId = 1, LotId = 1, Name = "CHMK",   },
                new Ticker{Id = 130, CompanyId = 130, ExchangeId = 1, LotId = 2, Name = "CHEP",   },
                new Ticker{Id = 131, CompanyId = 131, ExchangeId = 1, LotId = 4, Name = "ENRU",   }
            });
            builder.Entity<ReportSource>().HasData(new ReportSource[]
            {
                new ReportSource{Id = 1, CompanyId = 1, Key="Investing", Value = "3m-co"},
                new ReportSource{Id = 2, CompanyId = 2, Key="Investing", Value = "abbott-laboratories"},
                new ReportSource{Id = 3, CompanyId = 3, Key="Investing", Value = "adobe-sys-inc"},
                new ReportSource{Id = 4, CompanyId = 4, Key="Investing", Value = "air-prods---chem"},
                new ReportSource{Id = 5, CompanyId = 5, Key="Investing", Value = "alibaba"},
                new ReportSource{Id = 6, CompanyId = 6, Key="Investing", Value = "align-technology"},
                new ReportSource{Id = 7, CompanyId = 7, Key="Investing", Value = "google-inc"},
                new ReportSource{Id = 8, CompanyId = 8, Key="Investing", Value = "amazon-com-inc"},
                new ReportSource{Id = 9, CompanyId = 9, Key="Investing", Value = "american-express"},
                new ReportSource{Id = 10, CompanyId = 10, Key="Investing", Value = "apple-computer-inc"},
                new ReportSource{Id = 11, CompanyId = 11, Key="Investing", Value = "applied-matls-inc"},
                new ReportSource{Id = 12, CompanyId = 12, Key="Investing", Value = "at-t"},
                new ReportSource{Id = 13, CompanyId = 13, Key="Investing", Value = "bank-of-america"},
                new ReportSource{Id = 14, CompanyId = 14, Key="Investing", Value = "becton-dickinsn"},
                new ReportSource{Id = 15, CompanyId = 15, Key="Investing", Value = "best-buy"},
                new ReportSource{Id = 16, CompanyId = 16, Key="Investing", Value = "biogen-idec-inc"},
                new ReportSource{Id = 17, CompanyId = 17, Key="Investing", Value = "boeing-co"},
                new ReportSource{Id = 18, CompanyId = 18, Key="Investing", Value = "carnival-corp-exch"},
                new ReportSource{Id = 19, CompanyId = 19, Key="Investing", Value = "charter-communications"},
                new ReportSource{Id = 20, CompanyId = 20, Key="Investing", Value = "chevron"},
                new ReportSource{Id = 21, CompanyId = 21, Key="Investing", Value = "cisco-sys-inc"},
                new ReportSource{Id = 22, CompanyId = 22, Key="Investing", Value = "coca-cola-co"},
                new ReportSource{Id = 23, CompanyId = 23, Key="Investing", Value = "comcast-corp-new"},
                new ReportSource{Id = 24, CompanyId = 24, Key="Investing", Value = "conoco-phillips"},
                new ReportSource{Id = 25, CompanyId = 25, Key="Investing", Value = "cummins-inc"},
                new ReportSource{Id = 26, CompanyId = 26, Key="Investing", Value = "danaher-corp"},
                new ReportSource{Id = 27, CompanyId = 27, Key="Investing", Value = "dominion-res"},
                new ReportSource{Id = 28, CompanyId = 28, Key="Investing", Value = "dover-corp"},
                new ReportSource{Id = 29, CompanyId = 29, Key="Investing", Value = "emerson-elec"},
                new ReportSource{Id = 30, CompanyId = 30, Key="Investing", Value = "facebook-inc"},
                new ReportSource{Id = 31, CompanyId = 31, Key="Investing", Value = "fidelity-natl-in"},
                new ReportSource{Id = 32, CompanyId = 32, Key="Investing", Value = "ford-motor-co"},
                new ReportSource{Id = 33, CompanyId = 33, Key="Investing", Value = "general-electric"},
                new ReportSource{Id = 34, CompanyId = 34, Key="Investing", Value = "general-mills"},
                new ReportSource{Id = 35, CompanyId = 35, Key="Investing", Value = "global-payments"},
                new ReportSource{Id = 36, CompanyId = 36, Key="Investing", Value = "honeywell-intl"},
                new ReportSource{Id = 37, CompanyId = 37, Key="Investing", Value = "ibm"},
                new ReportSource{Id = 38, CompanyId = 38, Key="Investing", Value = "illumina,-inc."},
                new ReportSource{Id = 39, CompanyId = 39, Key="Investing", Value = "intel-corp"},
                new ReportSource{Id = 40, CompanyId = 40, Key="Investing", Value = "johnson-johnson"},
                new ReportSource{Id = 41, CompanyId = 41, Key="Investing", Value = "dr-pepper-snapple"},
                new ReportSource{Id = 42, CompanyId = 42, Key="Investing", Value = "kinder-morgan"},
                new ReportSource{Id = 43, CompanyId = 43, Key="Investing", Value = "kraft-foods-inc"},
                new ReportSource{Id = 44, CompanyId = 44, Key="Investing", Value = "lam-research-corp"},
                new ReportSource{Id = 45, CompanyId = 45, Key="Investing", Value = "lenzoloto-oao"},
                new ReportSource{Id = 46, CompanyId = 46, Key="Investing", Value = "live-nation-entertainment-inc"},
                new ReportSource{Id = 47, CompanyId = 47, Key="Investing", Value = "lockheed-martin"},
                new ReportSource{Id = 48, CompanyId = 48, Key="Investing", Value = "masco-corp"},
                new ReportSource{Id = 49, CompanyId = 49, Key="Investing", Value = "mastercard-cl-a"},
                new ReportSource{Id = 50, CompanyId = 50, Key="Investing", Value = "medtronic"},
                new ReportSource{Id = 51, CompanyId = 51, Key="Investing", Value = "merck---co"},
                new ReportSource{Id = 52, CompanyId = 52, Key="Investing", Value = "micron-tech"},
                new ReportSource{Id = 53, CompanyId = 53, Key="Investing", Value = "microsoft-corp"},
                new ReportSource{Id = 54, CompanyId = 54, Key="Investing", Value = "mondelez-international-inc"},
                new ReportSource{Id = 55, CompanyId = 55, Key="Investing", Value = "netflix,-inc."},
                new ReportSource{Id = 56, CompanyId = 56, Key="Investing", Value = "newmont-mining"},
                new ReportSource{Id = 57, CompanyId = 57, Key="Investing", Value = "nextera-energy-inc"},
                new ReportSource{Id = 58, CompanyId = 58, Key="Investing", Value = "northrop-grumman"},
                new ReportSource{Id = 59, CompanyId = 59, Key="Investing", Value = "norwegian-cruise-line-holdings-ltd"},
                new ReportSource{Id = 60, CompanyId = 60, Key="Investing", Value = "nvidia-corp"},
                new ReportSource{Id = 61, CompanyId = 61, Key="Investing", Value = "oracle-corp"},
                new ReportSource{Id = 62, CompanyId = 62, Key="Investing", Value = "palo-alto-netwrk"},
                new ReportSource{Id = 63, CompanyId = 63, Key="Investing", Value = "parkerhannifin"},
                new ReportSource{Id = 64, CompanyId = 64, Key="Investing", Value = "paypal-holdings-inc"},
                new ReportSource{Id = 65, CompanyId = 65, Key="Investing", Value = "pepsico"},
                new ReportSource{Id = 66, CompanyId = 66, Key="Investing", Value = "pfizer"},
                new ReportSource{Id = 67, CompanyId = 67, Key="Investing", Value = "polymetal-financial-summary"},
                new ReportSource{Id = 68, CompanyId = 68, Key="Investing", Value = "qualcomm-inc"},
                new ReportSource{Id = 69, CompanyId = 69, Key="Investing", Value = "united-tech"},
                new ReportSource{Id = 70, CompanyId = 70, Key="Investing", Value = "reliance-steel---aluminum-co."},
                new ReportSource{Id = 71, CompanyId = 71, Key="Investing", Value = "royal-caribbean"},
                new ReportSource{Id = 72, CompanyId = 72, Key="Investing", Value = "rpm-intl-inc"},
                new ReportSource{Id = 73, CompanyId = 73, Key="Investing", Value = "salesforce-com"},
                new ReportSource{Id = 74, CompanyId = 74, Key="Investing", Value = "sherwinwilliams"},
                new ReportSource{Id = 75, CompanyId = 75, Key="Investing", Value = "sirius-satellite-radio-inc"},
                new ReportSource{Id = 76, CompanyId = 76, Key="Investing", Value = "southern-co"},
                new ReportSource{Id = 77, CompanyId = 77, Key="Investing", Value = "southern-copper-corp."},
                new ReportSource{Id = 78, CompanyId = 78, Key="Investing", Value = "sth-west-airlines"},
                new ReportSource{Id = 79, CompanyId = 79, Key="Investing", Value = "tcs-group-holding-plc"},
                new ReportSource{Id = 80, CompanyId = 80, Key="Investing", Value = "tesla-motors"},
                new ReportSource{Id = 81, CompanyId = 81, Key="Investing", Value = "twitter-inc"},
                new ReportSource{Id = 82, CompanyId = 82, Key="Investing", Value = "verizon-communications"},
                new ReportSource{Id = 83, CompanyId = 83, Key="Investing", Value = "vertex-pharm"},
                new ReportSource{Id = 84, CompanyId = 84, Key="Investing", Value = "visa-inc"},
                new ReportSource{Id = 85, CompanyId = 85, Key="Investing", Value = "disney"},
                new ReportSource{Id = 86, CompanyId = 86, Key="Investing", Value = "wells-fargo"},
                new ReportSource{Id = 87, CompanyId = 87, Key="Investing", Value = "x5-retail-grp"},
                new ReportSource{Id = 88, CompanyId = 88, Key="Investing", Value = "yandex"},
                new ReportSource{Id = 89, CompanyId = 89, Key="Investing", Value = "yy-inc"},
                new ReportSource{Id = 90, CompanyId = 90, Key="Investing", Value = "akron_rts"},
                new ReportSource{Id = 91, CompanyId = 91, Key="Investing", Value = "alrosa-ao"},
                new ReportSource{Id = 92, CompanyId = 92, Key="Investing", Value = "vtb_rts"},
                new ReportSource{Id = 93, CompanyId = 93, Key="Investing", Value = "gazprom_rts"},
                new ReportSource{Id = 94, CompanyId = 94, Key="Investing", Value = "detskiy-mir-pao"},
                new ReportSource{Id = 95, CompanyId = 95, Key="Investing", Value = "amo-zil"},
                new ReportSource{Id = 96, CompanyId = 96, Key="Investing", Value = "human-stem-cells-institute"},
                new ReportSource{Id = 97, CompanyId = 97, Key="Investing", Value = "irkut-corp"},
                new ReportSource{Id = 98, CompanyId = 98, Key="Investing", Value = "kamaz"},
                new ReportSource{Id = 99, CompanyId = 99, Key="Investing", Value = "kuibyshevazot"},
                new ReportSource{Id = 100, CompanyId = 100, Key="Investing", Value = "levenguk-oao"},
                new ReportSource{Id = 101, CompanyId = 101, Key="Investing", Value = "lenta-ltd"},
                new ReportSource{Id = 102, CompanyId = 102, Key="Investing", Value = "lukoil_rts"},
                new ReportSource{Id = 103, CompanyId = 103, Key="Investing", Value = "megafon-oao"},
                new ReportSource{Id = 104, CompanyId = 104, Key="Investing", Value = "sg-mechel_rts"},
                new ReportSource{Id = 105, CompanyId = 105, Key="Investing", Value = "mmk_rts"},
                new ReportSource{Id = 106, CompanyId = 106, Key="Investing", Value = "moskovskiy-kreditnyi-bank-oao"},
                new ReportSource{Id = 107, CompanyId = 107, Key="Investing", Value = "mosenergo_rts"},
                new ReportSource{Id = 108, CompanyId = 108, Key="Investing", Value = "mrsk-volgi"},
                new ReportSource{Id = 109, CompanyId = 109, Key="Investing", Value = "mts_rts"},
                new ReportSource{Id = 110, CompanyId = 110, Key="Investing", Value = "nkhp-pao"},
                new ReportSource{Id = 111, CompanyId = 111, Key="Investing", Value = "novatek_rts"},
                new ReportSource{Id = 112, CompanyId = 112, Key="Investing", Value = "gmk-noril-nickel_rts"},
                new ReportSource{Id = 113, CompanyId = 113, Key="Investing", Value = "united-aircraft-corporation"},
                new ReportSource{Id = 114, CompanyId = 114, Key="Investing", Value = "omz-(pref)"},
                new ReportSource{Id = 115, CompanyId = 115, Key="Investing", Value = "polyus-zoloto_rts"},
                new ReportSource{Id = 116, CompanyId = 116, Key="Investing", Value = "rsc-energia"},
                new ReportSource{Id = 117, CompanyId = 117, Key="Investing", Value = "rosbank"},
                new ReportSource{Id = 118, CompanyId = 118, Key="Investing", Value = "rosneft_rts"},
                new ReportSource{Id = 119, CompanyId = 119, Key="Investing", Value = "rostelecom"},
                new ReportSource{Id = 120, CompanyId = 120, Key="Investing", Value = "gidroogk-011d"},
                new ReportSource{Id = 121, CompanyId = 121, Key="Investing", Value = "sberbank_rts"},
                new ReportSource{Id = 122, CompanyId = 122, Key="Investing", Value = "severstal_rts"},
                new ReportSource{Id = 123, CompanyId = 123, Key="Investing", Value = "seligdar"},
                new ReportSource{Id = 124, CompanyId = 124, Key="Investing", Value = "sollers"},
                new ReportSource{Id = 125, CompanyId = 125, Key="Investing", Value = "surgutneftegas_rts"},
                new ReportSource{Id = 126, CompanyId = 126, Key="Investing", Value = "tza-oao"},
                new ReportSource{Id = 127, CompanyId = 127, Key="Investing", Value = "tmk"},
                new ReportSource{Id = 128, CompanyId = 128, Key="Investing", Value = "phosagro"},
                new ReportSource{Id = 129, CompanyId = 129, Key="Investing", Value = "chmk"},
                new ReportSource{Id = 130, CompanyId = 130, Key="Investing", Value = "chtpz"},
                new ReportSource{Id = 131, CompanyId = 131, Key="Investing", Value = "ogk-5"}
            });
            #endregion
        }
    }
}
